version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    container_name: lumpick-db
    environment:
      - POSTGRES_USER=lumpick-org
      - POSTGRES_PASSWORD=fJWof4L+WyZkd68z
      - POSTGRES_DB=lumpick
    volumes:
      - lumpick:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  lumpick:
